apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: life-service
resources:
  - ../../base
images:
  - name: life-service-backend
    newName: life-service-backend
    newTag: local
  - name: life-service-frontend
    newName: life-service-frontend
    newTag: local
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: life-service-secret
    literals:
      - MYSQL_ROOT_PASSWORD=root
